// <auto-generated />
using System;
using Comeback.Rating.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comeback.Rating.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RatingDbContext))]
    partial class RatingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comeback.Rating.Domain.Entities.AwardedMatchXp", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awarded_at");

                    b.HasKey("MatchId", "UserId");

                    b.ToTable("awarded_match_xp", (string)null);
                });

            modelBuilder.Entity("Comeback.Rating.Domain.Entities.PlayerXp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CareerXp")
                        .HasColumnType("integer")
                        .HasColumnName("career_xp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MatchXp")
                        .HasColumnType("integer")
                        .HasColumnName("match_xp");

                    b.Property<int>("SeniorSeasons")
                        .HasColumnType("integer")
                        .HasColumnName("senior_seasons");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("YouthSeasons")
                        .HasColumnType("integer")
                        .HasColumnName("youth_seasons");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("player_xp", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
