<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="MassTransit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\services\notification\Comeback.Notification.Application\Comeback.Notification.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\services\notification\Comeback.Notification.Infrastructure\Comeback.Notification.Infrastructure.csproj" />
  </ItemGroup>

</Project>
